search_phrases:
  - western financial
  - western coast
  - wyatt dowling
products:
  - Home
  - Car
  - Business
  - Farm
  - Life
ai_platforms:
  - CHATGPT
  - PERPLEXITY
  - GEMINI
  - CLAUDE
competitors:
  - co-operators
  - westland
  - brokerlink
  - acera
locations:
  - Alix
  - Assiniboia
  - Barrhead
  - Bashaw
  - Bassano
  - Beaverlodge
  - Bolton
  - Bow Island
  - Brandon
  - Brooks
  - Campbell River
  - Camrose
  - Chase
  - Claresholm
  - Cochrane
  - Cold Lake
  - Coleman
  - Coquitlam
  - Coronation
  - Cranbrook
  - Creston
  - Dawson Creek
  - Drumheller
  - Duncan
  - Edmonton
  - Edson
  - Elkford
  - Estevan
  - Fairview
  - Fernie
  - Fort Nelson
  - Fort St. John
  - Fraser Lake
  - Fruitvale
  - Gilbert Plains
  - Glenavon
  - Golden
  - Grande Cache
  - Grande Prairie
  - Grimshaw
  - Gull Lake
  - Hanna
  - High River
  - Houston
  - Kaslo
  - Kelowna
  - Kimberley
  - King City
  - Lac La Biche
  - Lacombe
  - Langley
  - Leduc
  - LeRoy
  - Lethbridge
  - Lloydminster
  - Mayerthorpe
  - Medicine Hat
  - Melfort
  - Mill Bay
  - Nanaimo
  - Nanton
  - Nipawin
  - North Battleford
  - Okotoks
  - Olds
  - One Hundred Mile House
  - Peace River
  - Pembroke
  - Pender Island
  - Petawawa
  - Prince Albert
  - Prince George
  - Red Deer
  - Richmond
  - Roblin
  - Rosetown
  - Saanichton
  - Salmo
  - Schomberg
  - Shaunavon
  - Sidney
  - Smithers
  - Sooke
  - Souris
  - Sparwood
  - Spruce Grove
  - Strathmore
  - Surrey
  - Swift Current
  - Taber
  - Terrace
  - Turner Valley
  - Vancouver
  - Vanderhoof
  - Vegreville
  - Vermilion
  - Vernon
  - Victoria
  - Vulcan
  - Wainwright
  - Watrous
  - West Kelowna
  - Weyburn
  - White Fox
  - Williams Lake
  - Willow Bunch
  - Winfield
  - Winnipeg
  - Wolseley
  - Yorkton
  - Charlottetown
  - Miramichi
  - Edmundston
  - Yarmouth
  - Moncton
  - Bedford
  - Tracadie
  - North Sydney
  - Fredericton
  - Cole Harbour
  - Woodstock
  - Saint John
  - Kensington
  - Barrington Passage
  - Digby
  - Summerside
  - Minto
  - Campbellton
  - Oromocto
  - Rothesay
  - Church Point
  - Bathurst
  - Blackville
  - Grand Manan
  - Petitcodiac
  - Bridgetown
  - Annapolis
  - Manitoba
  - Alberta
  - British Columbia
  - Saskatchewan
  - Ontario
  - Canada
